from .color_str import print_err, print_colored_text, print_error_types
from .banded_editdistance import banded_edit_path, compute_cer
from .util import extract_transcription_from_page_xml, main_extract_transcription_from_page_xml, load_textline_pairs